/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Define to 1 if you have the `fpvm3' library (-lfpvm3). */
/* #undef HAVE_LIBFPVM3 */

/* Define to 1 if you have the `gpvm3' library (-lgpvm3). */
/* #undef HAVE_LIBGPVM3 */

/* Define to 1 if you have the `mpi' library (-lmpi). */
/* #undef HAVE_LIBMPI */

/* Define to 1 if you have the `pvm3' library (-lpvm3). */
/* #undef HAVE_LIBPVM3 */

/* Name of package */
#define PACKAGE "sweep3d"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "pakin@lanl.gov"

/* Define to the full name of this package. */
#define PACKAGE_NAME "SWEEP3D"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "SWEEP3D 2.2b"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "sweep3d"

/* Define to the version of this package. */
#define PACKAGE_VERSION "2.2b"

/* Version number of package */
#define VERSION "2.2b"
