#!/bin/bash

#mkdir bin

#make ft CLASS=D NPROCS=1
make ft CLASS=D NPROCS=2
make ft CLASS=D NPROCS=4
make ft CLASS=D NPROCS=8
make ft CLASS=D NPROCS=16
make ft CLASS=D NPROCS=32
make ft CLASS=D NPROCS=64
make ft CLASS=D NPROCS=128
make ft CLASS=D NPROCS=256
make ft CLASS=D NPROCS=512
make ft CLASS=D NPROCS=1024
make ft CLASS=D NPROCS=2048
