#!/bin/bash

#mkdir bin

make lu CLASS=C NPROCS=1
make lu CLASS=C NPROCS=2
make lu CLASS=C NPROCS=4
make lu CLASS=C NPROCS=8
make lu CLASS=C NPROCS=16
make lu CLASS=C NPROCS=32
make lu CLASS=C NPROCS=64
make lu CLASS=C NPROCS=128
make lu CLASS=C NPROCS=256
make lu CLASS=C NPROCS=512
make lu CLASS=C NPROCS=1024
make lu CLASS=C NPROCS=2048
